services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${MW_DB_USER}
      POSTGRES_PASSWORD: ${MW_DB_PASSWORD}
      POSTGRES_DB: ${MW_DB_NAME}
      PGUSER: ${MW_DB_USER}
    volumes:
      - db_data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U ${MW_DB_USER} -d ${MW_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 50

  redis:
    image: redis/redis-stack-server:latest
    expose:
      - "6379"

  prepare-config:
    image: alpine
    volumes:
      - shared_config:/conf
    command: >
      sh -c "apk add --no-cache jq >/dev/null 2>&1 && \
      jq -n \
      --arg prod 1 \
      --arg host \"$MW_DB_HOST\" \
      --arg port \"$MW_DATABASE_PORT\" \
      --arg name \"$MW_DB_NAME\" \
      --arg user \"$MW_DB_USER\" \
      --arg pass \"$MW_DB_PASSWORD\" \
      --arg key \"$MW_encryptKey\" \
      --arg cookie \"$MW_COOKIE_HTTPS_ONLY\" \
      --arg domain \"$MW_DOMAIN_NAME\" \
      --arg cors \"$MW_CORS_ALLOW_ORIGIN\" \
      '{PYSRV_IS_PRODUCTION: $prod, PYSRV_DATABASE_HOST: $host, PYSRV_DATABASE_HOST_POSTGRESQL: $host, PYSRV_DATABASE_PORT: $port, PYSRV_DATABASE_NAME: $name, PYSRV_DATABASE_USER: $user, PYSRV_DATABASE_PASSWORD: $pass, PYSRV_CRYPT_KEY: $key, PYSRV_BACKUP_FOLDER: \"/conf/backups\", PYSRV_FIRM_FOLDER: \"/conf/firmware\", PYSRV_COOKIE_HTTPS_ONLY: $cookie, PYSRV_REDIS_HOST: \"redis\", PYSRV_DOMAIN_NAME: $domain, PYSRV_CORS_ALLOW_ORIGIN: $cors}' \
      > /conf/server-conf.json"

  mikroman:
    build:
      context: ./mikroman
      dockerfile: Dockerfile
    entrypoint: bash -c "cd /app && ./init.sh"
    environment:
      - MW_SERVER_IP=${MW_SERVER_IP}
      - MW_RAD_SECRET=${MW_RAD_SECRET}
      - MW_DB_PASSWORD=${MW_DB_PASSWORD}
      - MW_DB_USER=${MW_DB_USER}
      - MW_DB_NAME=${MW_DB_NAME}
      - MW_encryptKey=${MW_encryptKey}
      - PYSRV_DATABASE_PORT=${MW_DATABASE_PORT}
      - PYSRV_IS_PRODUCTION=1
      - PYSRV_DATABASE_HOST=postgres
      - PYSRV_CRYPT_KEY=${MW_encryptKey}
      - PYSRV_COOKIE_HTTPS_ONLY=${MW_COOKIE_HTTPS_ONLY}
      - PYSRV_REDIS_HOST=redis
      - PYSRV_CORS_ALLOW_ORIGIN=${MW_CORS_ALLOW_ORIGIN}
    volumes:
      - shared_config:/conf
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    
  mikrofront:
    build:
      context: ./mikrofront
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - ./mikrofront/nginx.conf:/etc/nginx/conf.d/default.conf
      - shared_config:/conf
    depends_on:
      - mikroman
volumes:
  db_data:
  shared_config:
