services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${MW_DB_USER}
      POSTGRES_PASSWORD: ${MW_DB_PASSWORD}
      POSTGRES_DB: ${MW_DB_NAME}
      PGUSER: ${MW_DB_USER}
    volumes:
      - db_data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U ${MW_DB_USER} -d ${MW_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 50

  redis:
    image: redis/redis-stack-server:latest
    expose:
      - "6379"

  mikroman:
    build:
      context: ./mikroman
      dockerfile: Dockerfile
    entrypoint: bash -c "cd /app && ./init.sh"
    environment:
      - MW_SERVER_IP=${MW_SERVER_IP}
      - MW_RAD_SECRET=${MW_RAD_SECRET}
      - MW_DB_PASSWORD=${MW_DB_PASSWORD}
      - MW_DB_USER=${MW_DB_USER}
      - MW_DB_NAME=${MW_DB_NAME}
      - MW_encryptKey=${MW_encryptKey}
      - PYSRV_IS_PRODUCTION=${PYSRV_IS_PRODUCTION},
      - PYSRV_DATABASE_HOST=postgres,
      - PYSRV_DATABASE_PORT=${PYSRV_DATABASE_PORT},
      - PYSRV_DATABASE_NAME=${PYSRV_DATABASE_NAME},
      - PYSRV_DATABASE_USER=${MW_DB_USER},
      - PYSRV_DATABASE_PASSWORD=${MW_DB_PASSWORD},
      - PYSRV_CRYPT_KEY=${MW_encryptKey},
      - PYSRV_COOKIE_HTTPS_ONLY=${PYSRV_COOKIE_HTTPS_ONLY},
      - PYSRV_REDIS_HOST=redis,
      - PYSRV_CORS_ALLOW_ORIGIN=${PYSRV_CORS_ALLOW_ORIGIN}
    volumes:
      - ${CONF_PATH}:/conf
      - ${FIRMWARE_PATH}:/conf/firmware
      - ${BACKUPS_PATH}:/conf/backups
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env


 
  mikrofront:
    build:
      context: ./mikrofront
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - ./mikrofront/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${CONF_PATH}:/conf
    depends_on:
      - mikroman
volumes:
  db_data:
