services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${MW_DB_USER}
      POSTGRES_PASSWORD: ${MW_DB_PASSWORD}
      POSTGRES_DB: ${MW_DB_NAME}
      PGUSER: ${MW_DB_USER}
    volumes:
      - db_data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U ${MW_DB_USER} -d ${MW_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 50

  redis:
    image: redis/redis-stack-server:latest
    expose:
      - "6379"

  prepare-config:
    image: alpine
    volumes:
      - shared_config:/conf
    command: >
      sh -c '
      printf "{\n\
      \"PYSRV_IS_PRODUCTION\": \"1\",\n\
      \"PYSRV_DATABASE_HOST\": \"%s\",\n\
      \"PYSRV_DATABASE_HOST_POSTGRESQL\": \"%s\",\n\
      \"PYSRV_DATABASE_PORT\": \"%s\",\n\
      \"PYSRV_DATABASE_NAME\": \"%s\",\n\
      \"PYSRV_DATABASE_USER\": \"%s\",\n\
      \"PYSRV_DATABASE_PASSWORD\": \"%s\",\n\
      \"PYSRV_CRYPT_KEY\": \"%s\",\n\
      \"PYSRV_BACKUP_FOLDER\": \"/conf/backups\",\n\
      \"PYSRV_FIRM_FOLDER\": \"/conf/firmware\",\n\
      \"PYSRV_COOKIE_HTTPS_ONLY\": \"%s\",\n\
      \"PYSRV_REDIS_HOST\": \"redis\",\n\
      \"PYSRV_DOMAIN_NAME\": \"%s\",\n\
      \"PYSRV_CORS_ALLOW_ORIGIN\": \"%s\"\n\
      }\n" \
      "${MW_DB_HOST}" "${MW_DB_HOST}" "${MW_DATABASE_PORT}" "${MW_DB_NAME}" \
      "${MW_DB_USER}" "${MW_DB_PASSWORD}" "${MW_encryptKey}" \
      "${MW_COOKIE_HTTPS_ONLY}" "${MW_DOMAIN_NAME}" "${MW_CORS_ALLOW_ORIGIN}" \
      > /conf/server-conf.json
      '

  mikroman:
    build:
      context: ./mikroman
      dockerfile: Dockerfile
    entrypoint: bash -c "cd /app && ./init.sh"
    environment:
      - MW_SERVER_IP=${MW_SERVER_IP}
      - MW_RAD_SECRET=${MW_RAD_SECRET}
      - MW_DB_PASSWORD=${MW_DB_PASSWORD}
      - MW_DB_USER=${MW_DB_USER}
      - MW_DB_NAME=${MW_DB_NAME}
      - MW_encryptKey=${MW_encryptKey}
      - PYSRV_DATABASE_PORT=${MW_DATABASE_PORT}
      - PYSRV_IS_PRODUCTION=1
      - PYSRV_DATABASE_HOST=postgres
      - PYSRV_CRYPT_KEY=${MW_encryptKey}
      - PYSRV_COOKIE_HTTPS_ONLY=${MW_COOKIE_HTTPS_ONLY}
      - PYSRV_REDIS_HOST=redis
      - PYSRV_CORS_ALLOW_ORIGIN=${MW_CORS_ALLOW_ORIGIN}
    volumes:
      - shared_config:/conf
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    
  mikrofront:
    build:
      context: ./mikrofront
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - ./mikrofront/nginx.conf:/etc/nginx/conf.d/default.conf
      - shared_config:/conf
    depends_on:
      - mikroman
volumes:
  db_data:
  shared_config:
